title: Cell In Silico
description: Molecules, Sequences to Diseases

url: http://algaebrown.github.com/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Research
   url: /research
 - title: Category
   url: /categories
 - title: Tags
   url: /tag
social:
   github: algaebrown
   twitter: hermuba
   facebook: 
   email: b101102109@tmu.edu.tw

google_analytics: ""